apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: events-{{ include "fluent-bit.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
